version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  
  backend:
    build:
      context: ./server/
      dockerfile: ./compose/Dockerfile
    volumes:
      - ./server:/src/app
    depends_on: 
     - mongo 
    environment:
     - MONGODB_URI=mongodb://mongo:27017/poll 
    ports:
      - "4000:4000"

  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./compose/Dockerfile
  #   volumes:
  #     - ./frontend:/src/app
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"