version: "3.2"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./backend/data:/data/db
  node:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
