version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - poll_app:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /usr/local/wait-for-it.sh postgres:5432 -- npm start
volumes:
  poll_app:
