version: "3.2"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27018
    volumes:
      - ./backend/data:/data/db
  react:
    build:
        context: ./frontend/
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - node
  node:
    build:
        context: ./backend/
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app/backend
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27018 -- npm start
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  