version: '3'
services:
  
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  
  web:
    build: .
    ports:
     - "8000:8000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/poll 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     